#[allow(unused_features)]
#[allow(unused_imports)]
#[allow(non_camel_case_types)]
#[allow(dead_code)]

// Automatically generated by the Flatbuffers compiler. Do not modify.
pub mod crate_path {
    use super::*;
    pub mod binary_encoding {
        use super::*;
        mod variables_type_generated;
        pub use self::variables_type_generated::*;
        mod frame_map_generated;
        pub use self::frame_map_generated::*;
        mod function_map_generated;
        pub use self::function_map_generated::*;
        mod map_generated;
        pub use self::map_generated::*;
    } // binary_encoding
} // neon
